### ISSUE TITLE
Typos in age dictionary will lead to "not provided" 

### ISSUE THREAD

**Issue by julesjacobsen** [monarch-initiative/phenopacket-store#57]
Switch to 'raw' view to see the highlighted lines:

https://github.com/monarch-initiative/phenopacket-store/blob/f23540248e6d174242eb2cc3e6e962f0377e8cfc/notebooks/FBXL4/FBXL4-curation.ipynb#L641C10-L644C36

Typos `monhts` and `mohts` instead of `months` e.g.

```python
'10 monhts': "P10M",
```

**Comment by pnrobinson** [comment]
@julesjacobsen 
The idea of this dictionary was to be able to take original data with all of its warts and convert it into correct phenopackets. In this example, the original data has '10 monhts' and we convert it to "P10M". 
In this particular case it would have been easier to fix the original data since it only occurs once. A more common use case is just that somebody is using a correct but idiosyncratic string such as "10 mon. &3d" some something like that.
Not sure if this is exactly what the bug was?

**Comment by julesjacobsen** [comment]
Ahhh! Sorry, I misunderstood the purpose of this. I didn't realise that it was for correcting mistakes.
