### ISSUE TITLE
all values for pos in vcfRecord are strings

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/phenopacket-store#97]
pos should be an int:
https://phenopacket-schema.readthedocs.io/en/latest/variant.html#vcfrecord

But all the values here are strings

(found by checking using [linkml-validate](https://linkml.io/linkml/data/validating-data.html))

E.g

```
find . -name "*.json" -exec grep -h '"pos"' {} \;  | head
                  "pos": "124756209",
                  "pos": "124758482",
                  "pos": "124756540",
                  "pos": "124758482",
                  "pos": "124756540",
                  "pos": "124762120",
                  "pos": "124756704",
                  "pos": "124762120",
                  "pos": "124756540",
                  "pos": "124758482",
```

**Comment by ielis** [comment]
Hi @cmungall 

I think there is no bug here. The Phenopacket Schema defines VcfRecord as following:

```protobuf
message VcfRecord {
  string genome_assembly = 1;
  string chrom = 2;
  uint64 pos = 3;
  string id = 4;
  string ref = 5;
  string alt = 6;
  string qual = 7;
  string filter = 8;
  string info = 9;
}
```

Note `uint64` as the `pos` field. Due to [some constraints](https://github.com/protocolbuffers/protobuf/issues/2679) related to Javascript, protobuf encodes `uint64` into  `str` when serializing to JSON.

This is also why the JSON-schema of `phenopacket-tools` [requires](https://github.com/phenopackets/phenopacket-tools/blob/fe5346ad17df12fbd8c0f5e7d72646f455e286a8/phenopacket-tools-validator-jsonschema/src/main/resources/org/phenopackets/phenopackettools/validator/jsonschema/vrsatile.json#L59) `pos` to be a `str` when in JSON/YAML format.

So, it is a bit odd, but I think `str` is correct, if protobuf is the source of truth.

<details>

<summary>The only issue is...</summary>
... that RTD <a href="https://phenopacket-schema.readthedocs.io/en/latest/variant.html#vcfrecord">requires</a> an <code>int</code> :scream: 
</details>

**Comment by cmungall** [comment]
I thought we agreed the documentation was the SoT? It clearly states positions are integers. 

IMO this is really odd. I'd strongly recommend merging this PR and before the current behavior becomes enshrined. For the protobuf users (surely a minority? Everyone uses json/jsonschema/pydantic) we can just have a minimal shim layer.

**Comment by cmungall** [comment]
Another option is to use `uint32`. This means we can't ever use phenopackets for plant genomes, but I think that's fine. But I think freeing ourselves from limitations of protobuf is best

**Comment by pnrobinson** [comment]
@cmungall 
thanks for finding this. I am not sure what to do since the software is now pretty entrenched and it is working in many places. 
In any case, the place to fix it, if we want to, is not here, it would be upstream in the library code! I think that given the software that we are now using for about 5 other projects, this is probably something we might need to live with, or is there some easy solution that will not cause other issues? @ielis

**Comment by cmungall** [comment]
It’s a tough one… my belief is that it’s better to take the short term
churn now for the better long term result but I may be in the minority here…
